# Generated by Django 6.0.2 on 2026-03-19 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100, unique=True)),
                ('beskrivelse', models.TextField(blank=True)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kategorier',
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='Nyhet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=300)),
                ('innhold', models.TextField()),
                ('publisert_dato', models.DateTimeField(default=django.utils.timezone.now)),
                ('opprettet_av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opprettede_nyheter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nyheter',
                'ordering': ['-publisert_dato'],
            },
        ),
        migrations.CreateModel(
            name='Oppdrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField()),
                ('sted', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('aapen', 'Åpen'), ('paagaar', 'Pågår'), ('fullfort', 'Fullført')], default='aapen', max_length=20)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oppdrag', to='core.kategori')),
                ('opprettet_av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opprettede_oppdrag', to=settings.AUTH_USER_MODEL)),
                ('pameldte', models.ManyToManyField(blank=True, related_name='pameldte_oppdrag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Oppdrag',
                'ordering': ['-opprettet'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('kan_hjelpe_med', models.TextField(blank=True, help_text='Hva kan du hjelpe til med?')),
                ('allergier_hensyn', models.TextField(blank=True, help_text='Allergier eller spesielle hensyn')),
                ('tilgjengelighet', models.TextField(blank=True, help_text='Når er du tilgjengelig?')),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiler',
                'ordering': ['-opprettet'],
            },
        ),
    ]
